In [ ]:
https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_clientes.csv

In [4]:
import pandas as pd

In [5]:
url ="https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_clientes.csv"
df = pd.read_csv(url)
df.head()

  id_cliente            cliente                  correo        ciudad
0      CL100   Comercial Díaz 0  cliente065@empresa.com     Santa Ana
1      CL101      Grupo Ideal 1    cliente131@correo.sv  San Salvador
2      CL102      Grupo Ideal 2  cliente211@empresa.com    San Miguel
3      CL103  Almacenes Prado 3    cliente329@gmail.com     Santa Ana
4      CL104    Soluciones CR 4    cliente441@gmail.com   La Libertad

In [8]:
#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  155 non-null    object
 1   cliente     155 non-null    object
 2   correo      152 non-null    object
 3   ciudad      155 non-null    object
dtypes: object(4)
memory usage: 5.0+ KB

id_cliente    0
cliente       0
correo        3
ciudad        0
dtype: int64

LIMPIEZA DE DATOS

In [9]:
# 1. Copia y normalización de nombres de columnas
clientes_new = df.copy()
clientes_new.columns = clientes_new.columns.str.strip().str.lower()

# 2. Limpieza de Texto
clientes_new['cliente'] = clientes_new['cliente'].astype(str).str.strip().str.title()
clientes_new['ciudad'] = clientes_new['ciudad'].astype(str).str.strip().str.title()

# 3. Eliminar duplicados
clientes_new = clientes_new.drop_duplicates()

# 4. Estandarización de Nulos
clientes_new = clientes_new.replace(r'^\s*$', pd.NA, regex=True)

In [11]:
# Expresión regular para validar correos electrónicos
regex_correo = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

# Creamos una columna temporal para marcar correos válidos
clientes_new['correo_valido'] = clientes_new['correo'].str.match(regex_correo, na=False)

In [12]:

import re
regex_correo = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

# 2. Crear una máscara de validación de correo
correo_formato_valido = clientes_new['correo'].str.match(regex_correo, na=False)

# 3. Separar datos válidos
validos_cl = clientes_new[
    clientes_new['id_cliente'].notna() &
    clientes_new['cliente'].notna() &
    (correo_formato_valido == True)
].copy()

# 4. Separar datos rechazados

rechazados_cl = clientes_new[
    clientes_new['id_cliente'].isna() |
    clientes_new['cliente'].isna() |
    (correo_formato_valido == False)
].copy()

# Verificar los resultados
print(f"Clientes con datos perfectos: {len(validos_cl)}")
print(f"Clientes rechazados (por nulos o correo inválido): {len(rechazados_cl)}")

Clientes con datos perfectos: 132
Clientes rechazados (por nulos o correo inválido): 18

In [13]:
#Motivo de Rechazo
regex_correo = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

def motivo_cliente(row):
    motivos = []


    if pd.isna(row['id_cliente']):
        motivos.append("id_vacio")


    if pd.isna(row['cliente']) or str(row['cliente']).lower() == 'nan':
        motivos.append("nombre_vacio")

    if pd.isna(row['correo']) or str(row['correo']).lower() == 'nan':
        motivos.append("correo_vacio")
    elif not re.match(regex_correo, str(row['correo'])):
        motivos.append("formato_correo_invalido")

    return ",".join(motivos)

rechazados_cl["motivo_rechazo"] = rechazados_cl.apply(motivo_cliente, axis=1)

In [14]:
# Exportar archivos procesados de Nuevos Clientes
validos_cl.to_csv("c_clientes_curated.csv", index=False)
rechazados_cl.to_csv("c_clientes_rejects.csv", index=False)

print("Archivos 'c_clientes_curated.csv' y 'c_clientes_rejects.csv' generados con éxito.")

Archivos 'c_clientes_curated.csv' y 'c_clientes_rejects.csv' generados con éxito.

Conectar BD a render

In [15]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 56.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [16]:
from sqlalchemy import create_engine
import pandas as pd

In [17]:
database_url = "postgresql://etl_user:KWIr9XJ0F6G6c8YE7pj9J9RzFgRA6wo5@dpg-d6qu5nlm5p6s73ea88hg-a.oregon-postgres.render.com/etl_seguros_ibd2"

In [18]:
engine = create_engine(database_url)

In [20]:
test = pd.read_sql("SELECT 1", engine)

In [21]:
print(test)

   ?column?
0         1

In [23]:
# 1. Asegúrate de que validos_cl solo tenga las columnas que quieres
# Quitamos 'correo_valido' para que no ensucie la base de datos
columnas_a_guardar = ['id_cliente', 'cliente', 'correo', 'ciudad']
validos_cl_final = validos_cl[columnas_a_guardar]

# 2. Usamos 'replace' para que la tabla en Render ahora tenga estos nombres
validos_cl_final.to_sql(
    'clientes_curated',
    engine,
    if_exists='replace',
    index=False
)

# 3. Hacemos lo mismo con los rechazados para que sean consistentes
rechazados_cl.to_sql(
    'clientes_rejects',
    engine,
    if_exists='replace',
    index=False
)

print("Tabla actualizada. Ahora los nombres son 'cliente', 'correo' y se incluyó 'ciudad'.")

Tabla actualizada. Ahora los nombres son 'cliente', 'correo' y se incluyó 'ciudad'.

In [24]:
# Validar los primeros 10 registros con la nueva estructura
pd.read_sql("SELECT * FROM clientes_curated LIMIT 10", engine)

  id_cliente                cliente                  correo        ciudad
0      CL100       Comercial Díaz 0  cliente065@empresa.com     Santa Ana
1      CL101          Grupo Ideal 1    cliente131@correo.sv  San Salvador
2      CL102          Grupo Ideal 2  cliente211@empresa.com    San Miguel
3      CL103      Almacenes Prado 3    cliente329@gmail.com     Santa Ana
4      CL104        Soluciones Cr 4    cliente441@gmail.com   La Libertad
5      CL105  Distribuciones Luna 5  cliente592@empresa.com     Santa Ana
6      CL106          Grupo Ideal 6  cliente619@outlook.com  San Salvador
7      CL107      Almacenes Prado 7   cliente75@empresa.com  San Salvador
8      CL108         Empresa Nova 8  cliente861@outlook.com     Santa Ana
9      CL109  Distribuciones Luna 9    cliente998@correo.sv   La Libertad

In [25]:
# Validar el conteo de clientes por ciudad
query_ciudades = """
SELECT
    ciudad,
    COUNT(id_cliente) as total_clientes
FROM clientes_curated
GROUP BY ciudad
ORDER BY total_clientes DESC
"""

pd.read_sql(query_ciudades, engine)

         ciudad  total_clientes
0     Santa Ana              37
1  San Salvador              35
2    San Miguel              31
3   La Libertad              29