In [ ]:
https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_ventas.csv

In [1]:
import pandas as pd

In [2]:
url ="https://raw.githubusercontent.com/BryanJimenezUtec/etl-data-pipeline2520552022/refs/heads/main/data/raw/C_ventas.csv"
df = pd.read_csv(url)
df.head()

  id_venta id_cliente       fecha    total
0    V9000      CL154  2024-10-25  4641.86
1    V9001      CL243  2024-06-29  1138.59
2    V9002      CL111  2024-01-25  1873.39
3    V9003      CL244  2024-01-26      NaN
4    V9004      CL243  2024-05-24  2208.24

In [3]:
#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_venta    248 non-null    object
 1   id_cliente  242 non-null    object
 2   fecha       239 non-null    object
 3   total       241 non-null    object
dtypes: object(4)
memory usage: 7.9+ KB

id_venta      0
id_cliente    6
fecha         9
total         7
dtype: int64

LIMPIEZA DE DATOS

In [4]:
ventas = df.copy()
ventas.columns = ventas.columns.str.strip().str.lower()

ventas['total'] = ventas['total'].astype(str).str.replace('$', '', regex=False)
ventas['total'] = ventas['total'].str.replace('USD', '', regex=False)
ventas['total'] = ventas['total'].str.replace(',', '', regex=False).str.strip()

# Convertimos a tipo numérico decimal
ventas['total'] = pd.to_numeric(ventas['total'], errors='coerce')

#  Limpieza de columna 'fecha'
ventas['fecha'] = pd.to_datetime(ventas['fecha'], errors='coerce')

#  Limpieza de IDs
ventas['id_venta'] = ventas['id_venta'].astype(str).str.strip().str.upper()
ventas['id_cliente'] = ventas['id_cliente'].astype(str).str.strip().str.upper()

#  Estandarización de nulos
ventas = ventas.replace(r'^\s*$', pd.NA, regex=True)

In [5]:
# Separar datos válidos y rechazados para Ventas

validos_vn = ventas[
    ventas['id_venta'].notna() &
    ventas['id_cliente'].notna() &
    ventas['fecha'].notna() &
    ventas['total'].notna()
].copy()

rechazados_vn = ventas[
    ventas['id_venta'].isna() |
    ventas['id_cliente'].isna() |
    ventas['fecha'].isna() |
    ventas['total'].isna()
].copy()

# Verificar los resultados en la consola
print(f"Ventas procesadas correctamente: {len(validos_vn)}")
print(f"Ventas con errores (fecha, total o nulos): {len(rechazados_vn)}")

Ventas procesadas correctamente: 221
Ventas con errores (fecha, total o nulos): 27

In [6]:
def motivo_venta(row):
    motivos = []

    # Validar ID de Venta
    if pd.isna(row['id_venta']) or str(row['id_venta']).lower() == 'nan':
        motivos.append("id_venta_vacio")

    # Validar ID de Cliente
    if pd.isna(row['id_cliente']) or str(row['id_cliente']).lower() == 'nan':
        motivos.append("id_cliente_vacio")

    # Validar Fecha (NaT ocurre si estaba vacía o el formato era erróneo)
    if pd.isna(row['fecha']):
        motivos.append("fecha_invalida_o_vacia")

    # Validar Total (NaN si no se pudo convertir a decimal tras quitar $ o USD)
    if pd.isna(row['total']):
        motivos.append("total_nulo_o_formato_error")

    return ",".join(motivos)

rechazados_vn["motivo_rechazo"] = rechazados_vn.apply(motivo_venta, axis=1)

#  Ver los primeros resultados de rechazados
print("Muestra de ventas rechazadas y sus motivos:")
print(rechazados_vn[['id_venta', 'total', 'motivo_rechazo']].head())

Muestra de ventas rechazadas y sus motivos:
   id_venta    total              motivo_rechazo
3     V9003      NaN  total_nulo_o_formato_error
12    V9012  1443.82      fecha_invalida_o_vacia
13    V9013  4083.42      fecha_invalida_o_vacia
25    V9025  2734.23      fecha_invalida_o_vacia
28    V9028      NaN  total_nulo_o_formato_error

In [7]:
# Exportar archivos procesados de Ventas
validos_vn.to_csv("c_ventas_curated.csv", index=False)
rechazados_vn.to_csv("c_ventas_rejects.csv", index=False)

print("Archivos 'c_ventas_curated.csv' y 'c_ventas_rejects.csv' generados con éxito.")

Archivos 'c_ventas_curated.csv' y 'c_ventas_rejects.csv' generados con éxito.

Conectar BD a render

In [8]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 39.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [9]:
from sqlalchemy import create_engine
import pandas as pd

In [10]:
database_url = "postgresql://etl_user:KWIr9XJ0F6G6c8YE7pj9J9RzFgRA6wo5@dpg-d6qu5nlm5p6s73ea88hg-a.oregon-postgres.render.com/etl_seguros_ibd2"

In [11]:
engine = create_engine(database_url)

In [12]:
test = pd.read_sql("SELECT 1", engine)

In [13]:
print(test)

   ?column?
0         1

In [14]:
# Cargar ventas válidas a PostgreSQL

validos_vn.to_sql(
    'ventas_curated',
    engine,
    if_exists='replace',
    index=False
)

#  Cargar registros rechazados de ventas
rechazados_vn.to_sql(
    'ventas_rejects',
    engine,
    if_exists='replace',
    index=False
)

print(f"Carga finalizada: {len(validos_vn)} ventas registradas en la base de datos.")

Carga finalizada: 221 ventas registradas en la base de datos.

In [15]:
# Validar los primeros 10 registros de la tabla de ventas
pd.read_sql("SELECT * FROM ventas_curated LIMIT 10", engine)

  id_venta id_cliente      fecha    total
0    V9000      CL154 2024-10-25  4641.86
1    V9001      CL243 2024-06-29  1138.59
2    V9002      CL111 2024-01-25  1873.39
3    V9004      CL243 2024-05-24  2208.24
4    V9005      CL239 2024-09-10  3072.44
5    V9006      CL235 2024-11-01  4716.52
6    V9007      CL102 2025-03-07  1218.65
7    V9008      CL243 2024-11-30   625.08
8    V9009      CL129 2024-12-10  1003.40
9    V9010      CL122 2024-08-28  4436.89